/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laundry.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Laundry_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Laundry_Interface
     */
    public Laundry_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPanel = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        Login_page = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Main_Interface = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        logoutB = new javax.swing.JButton();
        laundryB = new javax.swing.JButton();
        customerB = new javax.swing.JButton();
        settingsB = new javax.swing.JButton();
        customerB1 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        laundryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laundryTable = new javax.swing.JTable();
        settingsPanel = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        customerTablePanel = new javax.swing.JPanel();
        customerInformation = new javax.swing.JPanel();
        f_name = new javax.swing.JTextField();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        l_name = new javax.swing.JTextField();
        cnumberLabel = new javax.swing.JLabel();
        c_number = new javax.swing.JTextField();
        jSrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        addCustomerBtn = new javax.swing.JButton();
        editCustomerBtn = new javax.swing.JButton();
        deleteCustomerBtn = new javax.swing.JButton();
        customerAddPanel = new javax.swing.JPanel();
        customerInformation1 = new javax.swing.JPanel();
        f_nameAdd = new javax.swing.JTextField();
        fnameLabel1 = new javax.swing.JLabel();
        lnameLabel1 = new javax.swing.JLabel();
        l_nameAdd = new javax.swing.JTextField();
        cnumberLabel1 = new javax.swing.JLabel();
        c_numberAdd = new javax.swing.JTextField();
        addCancelBtn = new javax.swing.JButton();
        addConfirmBtn = new javax.swing.JButton();
        customerEditPanel = new javax.swing.JPanel();
        customerInformation2 = new javax.swing.JPanel();
        f_nameEdit = new javax.swing.JTextField();
        fnameLabel2 = new javax.swing.JLabel();
        lnameLabel2 = new javax.swing.JLabel();
        l_nameEdit = new javax.swing.JTextField();
        cnumberLabel2 = new javax.swing.JLabel();
        c_numberEdit = new javax.swing.JTextField();
        editCancelBtn = new javax.swing.JButton();
        editConfirmBtn = new javax.swing.JButton();
        customerDeletePanel = new javax.swing.JPanel();
        customerInformation3 = new javax.swing.JPanel();
        f_nameDelete = new javax.swing.JTextField();
        fnameLabel3 = new javax.swing.JLabel();
        lnameLabel3 = new javax.swing.JLabel();
        l_nameDelete = new javax.swing.JTextField();
        cnumberLabel3 = new javax.swing.JLabel();
        c_numberDelete = new javax.swing.JTextField();
        deleteCancelBtn = new javax.swing.JButton();
        deleteConfirmBtn = new javax.swing.JButton();

        addPanel.setPreferredSize(new java.awt.Dimension(618, 380));

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(190, 60));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setLayout(new java.awt.CardLayout());

        Login_page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Password");

        jTextField2.setText("Username");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        Login_page.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        container.add(Login_page, "card2");

        Main_Interface.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutB.setText("Logout");
        logoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBActionPerformed(evt);
            }
        });
        navBar.add(logoutB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        laundryB.setText("Laundry");
        laundryB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryBActionPerformed(evt);
            }
        });
        navBar.add(laundryB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        customerB.setText("Laundry Log");
        customerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBActionPerformed(evt);
            }
        });
        navBar.add(customerB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        settingsB.setText("Settings");
        settingsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBActionPerformed(evt);
            }
        });
        navBar.add(settingsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 40));

        customerB1.setText("Customer Log");
        customerB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerB1ActionPerformed(evt);
            }
        });
        navBar.add(customerB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 40));

        Main_Interface.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 380));

        contentPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LAUNDRY QUEUE");

        laundryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Queue", "Name", "Contact No.", "Kg", "Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(laundryTable);
        if (laundryTable.getColumnModel().getColumnCount() > 0) {
            laundryTable.getColumnModel().getColumn(0).setResizable(false);
            laundryTable.getColumnModel().getColumn(1).setResizable(false);
            laundryTable.getColumnModel().getColumn(2).setResizable(false);
            laundryTable.getColumnModel().getColumn(3).setResizable(false);
            laundryTable.getColumnModel().getColumn(4).setResizable(false);
            laundryTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout laundryPanelLayout = new javax.swing.GroupLayout(laundryPanel);
        laundryPanel.setLayout(laundryPanelLayout);
        laundryPanelLayout.setHorizontalGroup(
            laundryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laundryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laundryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        laundryPanelLayout.setVerticalGroup(
            laundryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laundryPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        contentPanel.add(laundryPanel, "card2");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        contentPanel.add(settingsPanel, "card4");

        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerTablePanel.setPreferredSize(new java.awt.Dimension(650, 380));

        customerInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });

        fnameLabel.setText("First Name");

        lnameLabel.setText("Last Name");

        l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameActionPerformed(evt);
            }
        });

        cnumberLabel.setText("Contact Number");

        c_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_numberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInformationLayout = new javax.swing.GroupLayout(customerInformation);
        customerInformation.setLayout(customerInformationLayout);
        customerInformationLayout.setHorizontalGroup(
            customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnumberLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_name, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(l_name)
                    .addComponent(c_number))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        customerInformationLayout.setVerticalGroup(
            customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameLabel))
                .addGap(12, 12, 12)
                .addGroup(customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnumberLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Contact Num."
            }
        ));
        jSrollPane2.setViewportView(customerTable);

        addCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCustomerBtn.setText("ADD");
        addCustomerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtnMouseClicked(evt);
            }
        });
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        editCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editCustomerBtn.setText("EDIT");
        editCustomerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        editCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerBtnActionPerformed(evt);
            }
        });

        deleteCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteCustomerBtn.setText("DELETE");
        deleteCustomerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerTablePanelLayout = new javax.swing.GroupLayout(customerTablePanel);
        customerTablePanel.setLayout(customerTablePanelLayout);
        customerTablePanelLayout.setHorizontalGroup(
            customerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTablePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(customerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSrollPane2)
                    .addGroup(customerTablePanelLayout.createSequentialGroup()
                        .addComponent(customerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(customerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        customerTablePanelLayout.setVerticalGroup(
            customerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerTablePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        customerPanel.add(customerTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contentPanel.add(customerPanel, "card3");

        customerAddPanel.setPreferredSize(new java.awt.Dimension(650, 380));

        customerInformation1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        f_nameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameAddActionPerformed(evt);
            }
        });

        fnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnameLabel1.setText("First Name");

        lnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnameLabel1.setText("Last Name");

        l_nameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameAddActionPerformed(evt);
            }
        });

        cnumberLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cnumberLabel1.setText("Contact Number");

        c_numberAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_numberAddActionPerformed(evt);
            }
        });

        addCancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCancelBtn.setText("CANCEL");
        addCancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelBtnActionPerformed(evt);
            }
        });

        addConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addConfirmBtn.setText("ADD");
        addConfirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInformation1Layout = new javax.swing.GroupLayout(customerInformation1);
        customerInformation1.setLayout(customerInformation1Layout);
        customerInformation1Layout.setHorizontalGroup(
            customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(addConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(customerInformation1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInformation1Layout.createSequentialGroup()
                        .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnameLabel1)
                            .addComponent(fnameLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_nameAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(f_nameAdd))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInformation1Layout.createSequentialGroup()
                        .addComponent(cnumberLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(c_numberAdd)))
                .addContainerGap())
        );
        customerInformation1Layout.setVerticalGroup(
            customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel1)
                    .addComponent(f_nameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnameLabel1)
                    .addComponent(l_nameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnumberLabel1)
                    .addComponent(c_numberAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(customerInformation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout customerAddPanelLayout = new javax.swing.GroupLayout(customerAddPanel);
        customerAddPanel.setLayout(customerAddPanelLayout);
        customerAddPanelLayout.setHorizontalGroup(
            customerAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerAddPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(customerInformation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        customerAddPanelLayout.setVerticalGroup(
            customerAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerAddPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(customerInformation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        contentPanel.add(customerAddPanel, "card2");

        customerInformation2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        f_nameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameEditActionPerformed(evt);
            }
        });

        fnameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnameLabel2.setText("First Name");

        lnameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnameLabel2.setText("Last Name");

        l_nameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameEditActionPerformed(evt);
            }
        });

        cnumberLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cnumberLabel2.setText("Contact Number");

        c_numberEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_numberEditActionPerformed(evt);
            }
        });

        editCancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editCancelBtn.setText("CANCEL");
        editCancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        editCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelBtnActionPerformed(evt);
            }
        });

        editConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editConfirmBtn.setText("EDIT");
        editConfirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        editConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInformation2Layout = new javax.swing.GroupLayout(customerInformation2);
        customerInformation2.setLayout(customerInformation2Layout);
        customerInformation2Layout.setHorizontalGroup(
            customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnumberLabel2)
                    .addComponent(lnameLabel2)
                    .addComponent(fnameLabel2))
                .addGap(18, 18, 18)
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_nameEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(c_numberEdit)
                    .addComponent(f_nameEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(customerInformation2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(editCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(editConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        customerInformation2Layout.setVerticalGroup(
            customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel2)
                    .addComponent(f_nameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnameLabel2)
                    .addComponent(l_nameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnumberLabel2)
                    .addComponent(c_numberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout customerEditPanelLayout = new javax.swing.GroupLayout(customerEditPanel);
        customerEditPanel.setLayout(customerEditPanelLayout);
        customerEditPanelLayout.setHorizontalGroup(
            customerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerEditPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(customerInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        customerEditPanelLayout.setVerticalGroup(
            customerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerEditPanelLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(customerInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        contentPanel.add(customerEditPanel, "card2");

        customerDeletePanel.setPreferredSize(new java.awt.Dimension(650, 380));

        customerInformation3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        f_nameDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameDeleteActionPerformed(evt);
            }
        });

        fnameLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnameLabel3.setText("First Name");

        lnameLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnameLabel3.setText("Last Name");

        l_nameDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameDeleteActionPerformed(evt);
            }
        });

        cnumberLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cnumberLabel3.setText("Contact Number");

        c_numberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_numberDeleteActionPerformed(evt);
            }
        });

        deleteCancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteCancelBtn.setText("CANCEL");
        deleteCancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCancelBtnActionPerformed(evt);
            }
        });

        deleteConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteConfirmBtn.setText("DELETE");
        deleteConfirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInformation3Layout = new javax.swing.GroupLayout(customerInformation3);
        customerInformation3.setLayout(customerInformation3Layout);
        customerInformation3Layout.setHorizontalGroup(
            customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnumberLabel3)
                    .addComponent(lnameLabel3)
                    .addComponent(fnameLabel3))
                .addGap(18, 18, 18)
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_nameDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(c_numberDelete)
                    .addComponent(f_nameDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(customerInformation3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(deleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(deleteConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        customerInformation3Layout.setVerticalGroup(
            customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInformation3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel3)
                    .addComponent(f_nameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnameLabel3)
                    .addComponent(l_nameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnumberLabel3)
                    .addComponent(c_numberDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerInformation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout customerDeletePanelLayout = new javax.swing.GroupLayout(customerDeletePanel);
        customerDeletePanel.setLayout(customerDeletePanelLayout);
        customerDeletePanelLayout.setHorizontalGroup(
            customerDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDeletePanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(customerInformation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        customerDeletePanelLayout.setVerticalGroup(
            customerDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDeletePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(customerInformation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        contentPanel.add(customerDeletePanel, "card2");

        Main_Interface.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 650, 380));

        container.add(Main_Interface, "card3");

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        container.removeAll();
        container.repaint();
        container.revalidate();
        container.add(Main_Interface);
        container.repaint();
        container.revalidate();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void laundryBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryBActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(laundryPanel);
        contentPanel.repaint();
        contentPanel.revalidate();     
    }//GEN-LAST:event_laundryBActionPerformed

    private void customerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBActionPerformed
 
    }//GEN-LAST:event_customerBActionPerformed

    private void settingsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(settingsPanel);
        contentPanel.repaint();
        contentPanel.revalidate();  
    }//GEN-LAST:event_settingsBActionPerformed

    private void logoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBActionPerformed

    private void customerB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerB1ActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerTablePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_customerB1ActionPerformed

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameActionPerformed

    private void c_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_numberActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerAddPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void f_nameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameAddActionPerformed

    private void l_nameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameAddActionPerformed

    private void c_numberAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_numberAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_numberAddActionPerformed

    private void addConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConfirmBtnActionPerformed
        String fname = f_nameAdd.getText();
        String lname = l_nameAdd.getText();
        String cnumber = c_numberAdd.getText();
        
        if (!fname.isEmpty() && !lname.isEmpty() && !cnumber.isEmpty()) {
            boolean isAdded = LaundrySystem.addCustomer(fname, lname, cnumber);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Customer added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                f_nameAdd.setText("");
                l_nameAdd.setText("");
                c_numberAdd.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add customer. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addConfirmBtnActionPerformed

    private void addCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerTablePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_addCancelBtnActionPerformed

    private void f_nameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameEditActionPerformed

    private void l_nameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameEditActionPerformed

    private void c_numberEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_numberEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_numberEditActionPerformed

    private void editCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerTablePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_editCancelBtnActionPerformed

    private void editConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfirmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editConfirmBtnActionPerformed

    private void f_nameDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameDeleteActionPerformed

    private void l_nameDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameDeleteActionPerformed

    private void c_numberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_numberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_numberDeleteActionPerformed

    private void deleteCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCancelBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerTablePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_deleteCancelBtnActionPerformed

    private void deleteConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConfirmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteConfirmBtnActionPerformed

    private void editCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerEditPanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_editCustomerBtnActionPerformed

    private void deleteCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerBtnActionPerformed
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(customerDeletePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_deleteCustomerBtnActionPerformed

    private void addCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundry_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_page;
    private javax.swing.JPanel Main_Interface;
    private javax.swing.JButton addCancelBtn;
    private javax.swing.JButton addConfirmBtn;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JPanel addPanel;
    private javax.swing.JTextField c_number;
    private javax.swing.JTextField c_numberAdd;
    private javax.swing.JTextField c_numberDelete;
    private javax.swing.JTextField c_numberEdit;
    private javax.swing.JLabel cnumberLabel;
    private javax.swing.JLabel cnumberLabel1;
    private javax.swing.JLabel cnumberLabel2;
    private javax.swing.JLabel cnumberLabel3;
    private javax.swing.JPanel container;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel customerAddPanel;
    private javax.swing.JButton customerB;
    private javax.swing.JButton customerB1;
    private javax.swing.JPanel customerDeletePanel;
    private javax.swing.JPanel customerEditPanel;
    private javax.swing.JPanel customerInformation;
    private javax.swing.JPanel customerInformation1;
    private javax.swing.JPanel customerInformation2;
    private javax.swing.JPanel customerInformation3;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel customerTablePanel;
    private javax.swing.JButton deleteCancelBtn;
    private javax.swing.JButton deleteConfirmBtn;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JButton editCancelBtn;
    private javax.swing.JButton editConfirmBtn;
    private javax.swing.JButton editCustomerBtn;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField f_nameAdd;
    private javax.swing.JTextField f_nameDelete;
    private javax.swing.JTextField f_nameEdit;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel fnameLabel1;
    private javax.swing.JLabel fnameLabel2;
    private javax.swing.JLabel fnameLabel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jSrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField l_name;
    private javax.swing.JTextField l_nameAdd;
    private javax.swing.JTextField l_nameDelete;
    private javax.swing.JTextField l_nameEdit;
    private javax.swing.JButton laundryB;
    private javax.swing.JPanel laundryPanel;
    private javax.swing.JTable laundryTable;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JLabel lnameLabel1;
    private javax.swing.JLabel lnameLabel2;
    private javax.swing.JLabel lnameLabel3;
    private javax.swing.JButton logoutB;
    private javax.swing.JPanel navBar;
    private javax.swing.JButton settingsB;
    private javax.swing.JPanel settingsPanel;
    // End of variables declaration//GEN-END:variables
}
